version: "3"
services:
  web:
    container_name: qiita-docker-compose-web
    build: 
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs:delegated
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    container_name: qiita-docker-compose-db
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
     timeout: 20s
     retries: 5

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080